import Link from 'next/link';
import { processSteps, handoffItems, site } from '@/content/site';
import { pageMetadata } from '@/lib/metadata';
import { Closing } from '@/components/Closing';
import styles from '@/components/pages.module.css';
export const metadata = pageMetadata('How It Works', 'A scoped implementation project, from the first request through access, testing, documentation and handoff.', '/how-it-works');
export default function Process() {
  return <div className="container"><div className="page-intro"><span className="eyebrow">How it works</span><h1>Clear from the start.<br />Complete at the finish.</h1><p>A defined implementation, with responsibilities, deliverables and acceptance criteria agreed before work begins.</p></div><div className={`page-body ${styles.steps}`}><ol className={styles.processList}>{processSteps.map((step, i) => <li key={step.title}><span className={styles.number} aria-hidden="true">0{i + 1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol></div><section className={`section ${styles.handoff}`}><div><span className="eyebrow">The handoff</span><h2>You know what’s there.<br />And how it was tested.</h2></div><ul>{handoffItems.map(item => <li key={item}>{item}</li>)}</ul></section><section className="section reading"><h2 style={{ marginTop: 0 }}>What completion means</h2><p>The agreed events and parameters behave as specified and arrive at their intended destinations within the documented test scope. Some platforms need processing time. A browser request and confirmed destination data are separate checks.</p><p>Campaign outcomes such as ROAS are not implementation acceptance criteria.</p><h2>Timing and later changes</h2><p>Delivery estimates begin once the necessary access and materials are available. Agency and developer responsibilities are agreed up front.</p><p>{site.correctionPolicyText}</p><p>Already agreed on a project? Read the <Link href="/getting-started">getting-started guide</Link>.</p></section><Closing /></div>;
}
