import Link from 'next/link';
import Image from 'next/image';
import type { CaseStudy as Case } from '@/content/work';
import { serviceTitle } from '@/content/services';
import { Arrow } from '../Arrow';
import { FlowDiagram } from '../FlowDiagram';
import styles from '../pages.module.css';
export function CaseStudy({ entry, fixture = false }: { entry: Case; fixture?: boolean }) {
  return <div className="container page-body"><div className={styles.caseIntro}>{fixture && <div className="notice" style={{ marginBottom: 32 }}>Development fixture. Illustrative content only; no completed implementation or live results.</div>}<span className={styles.evidenceLabel}>{entry.evidenceType}</span><h1>{entry.title}</h1><p>{entry.summary}</p></div>
    {entry.hero && <figure className={styles.caseFigure}><Image src={entry.hero.src} alt={entry.hero.alt} width={entry.hero.width} height={entry.hero.height} sizes="(max-width: 767px) 100vw, 1280px" /><figcaption>{entry.hero.caption}</figcaption></figure>}
    <div className={styles.caseLayout}><article className={styles.caseArticle}><section><h2>The requirement</h2><p>{entry.requirement}</p></section><section><h2>Scope of the implementation</h2><ul>{entry.scope.map(text => <li key={text}>{text}</li>)}</ul></section>{fixture && <section><h2>An illustrative data flow</h2><FlowDiagram /></section>}<section><h2>What was implemented</h2>{entry.implementation.map(text => <p key={text}>{text}</p>)}</section><section><h2>Verification evidence</h2><div className={styles.evidenceTable} role="region" aria-label="Verification evidence, scroll horizontally on small screens" tabIndex={0}><table><thead><tr><th scope="col">Scenario</th><th scope="col">Expected behavior</th><th scope="col">Observed result</th></tr></thead><tbody>{entry.verification.map(row => <tr key={row.scenario}><td>{row.scenario}</td><td>{row.expected}</td><td>{row.observed}</td></tr>)}</tbody></table></div></section><section><h2>Challenges and resolutions</h2><p>{entry.challenges}</p></section><section><h2>Limitations</h2><p>{entry.limitations}</p></section>
      {(entry.demoUrl || entry.videoUrl || entry.artifacts?.length) && <section><h2>Explore the evidence</h2><div className="actions">{entry.demoUrl && <a href={entry.demoUrl} className="text-link" target="_blank" rel="noopener noreferrer">Open live demo <Arrow /></a>}{entry.videoUrl && <a href={entry.videoUrl} className="text-link" target="_blank" rel="noopener noreferrer">Watch the walkthrough <Arrow /></a>}{entry.artifacts?.map(link => <a key={link.url} href={link.url}>{link.label}</a>)}</div></section>}
      <div className="actions"><Link className="button" href={`/contact?service=${entry.serviceIds[0]}`}>Request a similar implementation <Arrow /></Link></div></article><aside className={styles.caseFacts}><dl><dt>Service</dt><dd>{entry.serviceIds.map(id => <p key={id}><Link href={`/services#${id}`}>{serviceTitle(id)}</Link></p>)}</dd><dt>Platforms</dt><dd>{entry.platforms.join(', ')}</dd><dt>Evidence type</dt><dd>{entry.evidenceType}</dd>{entry.lastVerifiedAt && <><dt>Last verified</dt><dd>{entry.lastVerifiedAt}</dd></>}</dl></aside></div></div>;
}
